accounts/urls.py
from django.conf.urls import url
from . import views

app_name ='accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_user, name="signup_user"),
    url(r'^login/$', views.login_user, name="login_user"),
    url(r'^logout/$', views.logout_user, name="logout_user"),
    url(r'^profile/$', views.user_profile, name="user_profile"),
    url(r'^show/(?P<user_id>\d+)/$', views.show_user_profile, name="show_user_profile"),
]

blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'

urlpatterns = [
    url(r'^$', views.portfolio, name='portfolio'),
    url(r'^list/$', views.list, name='list'),
    url(r'^about/$', views.about, name="about"),
    url(r'^announcements/$', views.announcements, name="announcements"),
    url(r'^calenders/$', views.calenders, name="calenders"),
    url(r'^create/$', views.create_blog, name='create_blog'),
    url(r'^confirm-delete/(?P<blog_id>\d+)/$', views.delete_blog_confirmation, name='delete_blog_confirmation'),
    url(r'^delete/(?P<blog_id>\d+)/$', views.delete_blog, name='delete_blog'),
    url(r'^delete-review/(?P<blog_review_id>\d+)/$', views.delete_blog_review, name='delete_blog_review'),
    url(r'^comment/(?P<blog_id>\d+)/$', views.comment_blog, name='comment_blog'),
    url(r'^edit/(?P<blog_id>\d+)/$', views.edit_blog, name='edit_blog'),
    url(r'^(?P<blog_id>\d+)/$', views.blog_detail, name='blog_detail'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
#for using the media file variables
from django.conf import settings
#for static files(css)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#for media files(images)
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('blog.urls')),
    url(r'^accounts/', include('accounts.urls')),
]
#appending url for static_files(css)
urlpatterns += staticfiles_urlpatterns()
#appending url for media_file(images)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField(blank=False)
    image = models.ImageField(default='default.png', blank = True)
    author = models.ForeignKey(User, default=None, on_delete='cascade')
    created_date = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'

    def __str__(self):
        return self.title

    def get_link(self):
        return self.id

    def snippet(self):
        if len(self.body) > 50:
            return self.body[:50]+' ...'
        else:
            return self.body

    def img_file_name(self):
        return self.image.path


class Blog_reviews(models.Model):
    blog = models.ForeignKey(Blog, default=None,on_delete=models.CASCADE)
    comment = models.TextField()
    author = models.ForeignKey(User, default=None, on_delete='cascade')
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Blog_reviews'
        verbose_name_plural = 'Blog_reviews'

    def __str__(self):
        return self.blog.title

blog/forms.py
from django import forms
from . import models

#form for creating new blog
class CreateBlog(forms.ModelForm):
    #to remove the currently and clear
    image = forms.ImageField(label=('Blog Image'), required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)

    class Meta:
        model = models.Blog
        fields = ('title','body','image')

#form for creating new blog review(comment)
class Blog_review_form(forms.ModelForm):
    class Meta:
        model = models.Blog_reviews
        fields = ('comment',)

#form for editing blog
class Edit_Blog(forms.ModelForm):
    #to remove the currently and clear
    image = forms.ImageField(label=('Blog Image'), required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)

    class Meta:
        model = models.Blog
        fields = ('title','body','image')

blog/views.py
#for displaying webpages
from django.shortcuts import render, redirect
#importing models
from .models import Blog, Blog_reviews
#for checking if the user is logged in
from django.contrib.auth.decorators import login_required
#for importing forms
from . import forms
#for deleting image files
import os
#for messages
from django.contrib import messages

#displaying list of all blogs
def list(request):
   #getting all blogs
   blogs = Blog.objects.all().order_by('-created_date')
   return render(request , 'blog/index.html', {'blogs': blogs})

#detail of a particular blog
def blog_detail(request, blog_id):
   #getting blog data
   blog = Blog.objects.get(id = blog_id)
   #getting blog comments
   reviews = Blog_reviews.objects.filter(blog = blog).order_by('-created_date')
   #To get the name of the current user(whether to show delete-btn and edit-btn or not)
   authorised = False
   if request.user.is_authenticated:
      user = request.user.username
      if str(blog.author) == user:
         authorised = True
   #dictionary to store data to be passed in the render function
   context = {'blog': blog,'authorised': authorised, 'reviews': reviews}
   return render(request, 'blog/blog_detail.html', context)

@login_required
def create_blog(request):
   #to create blog(post data and create blog)
   if request.method == 'POST':
      form = forms.CreateBlog(request.POST, request.FILES)
      if form.is_valid():
         data = form.save(commit=False)
         data.author = request.user
         data.save()
         msg = 'Your blog has been created!'
         messages.success(request, msg)
      return redirect('blog:list')
   #to create blog(create form and get data)
   else:
      form = forms.CreateBlog()
   return render(request, 'blog/blog_create.html', {'form': form})


@login_required
def delete_blog(request, blog_id):
   #getting data of the blog
   blog = Blog.objects.get(pk = blog_id)
   author = blog.author
   img = blog.img_file_name()

   #checking if the author of the blog and the currently logged in user are the same
   if request.user == author:
      blog.delete()
      #delete the image from images folder
      if not 'default.png' in img:
         os.remove(img)
      #showing success msg
      msg = 'Blog has been deleted!'
      messages.success(request, msg)
   return redirect('blog:list')


@login_required
def delete_blog_review(request, blog_review_id):
   review = Blog_reviews.objects.get(pk = blog_review_id)
   author = review.author

   #checking if the author of the blog and the currently logged in user are the same
   if request.user == author:
      review.delete()
      #showing success msg
      msg = 'Comment has been deleted!'
      messages.success(request, msg)
   return redirect('blog:blog_detail', blog_id = review.blog.pk)


@login_required
def comment_blog(request, blog_id):
   #getting data of the blog
   blog = Blog.objects.get(pk=blog_id)
   #to comment blog(post data and comment blog)
   if request.method == 'POST':
      form = forms.Blog_review_form(request.POST)
      if form.is_valid():
         review = form.save(commit=False)
         review.blog = blog
         review.author = request.user
         # review.author = request.user
         review.save()
         return redirect('blog:blog_detail', blog_id = review.blog.pk)
   #to comment blog(create form and get data)
   else:
      form = forms.Blog_review_form()
   #dictionary to store data to be passed in the render function
   context = {'form': form, 'blog_id': blog_id}
   return render(request, 'blog/comment_blog.html', context)

@login_required
def edit_blog(request, blog_id):
   #getting data of the blog
   blog = Blog.objects.get(pk=blog_id)
   #if the current user and the author of the blog are same
   if blog.author == request.user:
      #to edit blog(post data and edit blog)
      if request.method == 'POST':
         form = forms.Edit_Blog(request.POST, request.FILES, instance=blog)
         if form.is_valid():
            form.save()
            return redirect('/'+str(blog_id))
      #to edit blog(create form and get data)
      else:
         form = forms.Edit_Blog(instance=blog)
      #dictionary to store data to be passed in the render function
      context = {'form': form,'blog':blog,'blog_id': blog_id}
      return render(request, 'blog/edit_blog.html', context)
   else:
      error_msg = 'Sorry! you are not authorised'
      return render(request, 'errors.html', {'error_msg':error_msg})

#confirmation for deletion of the blog
@login_required
def delete_blog_confirmation(request, blog_id):
   return render(request, 'blog/delete-confirmation.html', {'blog_id': blog_id})

#displaying the about page
def about(request):
    return render(request, 'about.html')

def announcements(request):
   msg = 'No announcements yet!'
   return render(request, 'informations.html', {'msg':msg})

def calenders(request):
   msg = 'No calenders yet!'
   return render(request, 'informations.html', {'msg':msg})

def portfolio(request):
   return render(request, 'portfolio.html')

templates/blog/blog_create.html
{% extends 'base-layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
<h1>Create a new Blog....</h1>
    <!-- In the below form enctype is used because we are posting image files using form -->
    <form action="{% url 'blog:create_blog' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Create Blog" class="btn btn-primary btn-lg btn-block btn-success">
    </form>
</div>

{% endblock %}

templates/blog/blog_detail.html
{% extends 'base-layout.html' %}

{% block content%}
<div class="content-section">
    <div>
    <h1 class="text-center">{{blog.title}}</h1>
    <!-- code to show delete btn  -->
    {% if authorised %}
    <a href="{% url 'blog:delete_blog_confirmation' blog_id=blog.pk %}" class="btn btn-danger btn-sm mt-1 mb-1">Delete</a>
    <a href="{% url 'blog:edit_blog' blog_id=blog.pk %}" class="btn btn-secondary btn-sm mt-1 mb-1">Edit</a>
    {% endif %}
    </div>

    <!-- the url is an inbuild property of blog.models.image -->
    <img src="{{blog.image.url}}" class="img-thumbnail">
    <div class="font-italic">
    <br>
    <p class="blog-body mt-1 mb-1">{{blog.body}}</p>
    </div>
    <br>
    <small class="font-weight-bold">Created on: {{blog.created_date}}</small>
    <br>
    <small class="font-weight-bold">Created by:-
        <a href="{% url 'accounts:show_user_profile' blog.author.id %}">{{blog.author}}</a>
    </small>
    <br>
    <div class="form-group">
    <a href="{% url 'blog:comment_blog' blog_id=blog.pk %}" class="btn btn-success mt-3">comment</a>
    </div>
</div>
<div class="content-section">
    {% if reviews%}
    <legend class="font-weight-bold">Comments</legend>
    {% for review in reviews %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
            <h5>By:-
            <a class="mr-2" href="{% url 'accounts:show_user_profile' review.author.id %}">{{ review.author.username }}</a>
            </h5>
            {% if review.author == user %}
            <a href="{% url 'blog:delete_blog_review' blog_review_id=review.pk %}" class="btn btn-danger btn-sm delete-comment">Delete</a>
            {% endif %}
            <p>{{ review.comment }}</p>
            <small>{{ review.created_date }}</small>
        </div>
    </article>
    {% endfor %}
    {% else %}
    <legend class="font-weight-bold">No comments yet!</legend>
    {% endif%}
</div>
{%endblock%}

templates/blog/comment_blog.html
{% extends 'base-layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section font-weight-bold">
<form action="{% url 'blog:comment_blog' blog_id %}" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Create">
</form>
</div>
{% endblock %}

templates/blog/delete-confirmation.html
{% extends 'base-layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
		<p class="font-weight-bold">Are your sure to delete the blog!!!</p>
		<a href="{% url 'blog:delete_blog' blog_id=blog_id %}" class="btn btn-danger">Delete</a>
		<a href="{% url 'blog:blog_detail' blog_id=blog_id %}" class="btn btn-secondary">Cancel</a>
	</div>
{% endblock %}

templates/blog/edit_blog.html
{% extends 'base-layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
<h1>Edit Blog</h1>
    <!-- In the below form enctype is used because we are posting image files using form -->
    <form action="{% url 'blog:edit_blog' blog_id%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Save Changes" class="btn btn-primary btn-lg btn-block btn-success">
    </form>
</div>

{% endblock %}

templates/blog/index.html
{% extends 'base-layout.html'%}

{% block content%}

{% if blogs%}

{% for blog in blogs%}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="{% url 'accounts:show_user_profile' blog.author.id %}">{{ blog.author }}</a>
            <small class="text-muted">{{ blog.created_date }}</small>
            </div>
            <h2><a class="article-title" href="/{{blog.get_link}}">{{ blog.title }}</a></h2>
            <p class="article-content">{{ blog.snippet }}</p>
        </div>
    </article>
{% endfor %}

{% else %}
<h2>No blogs available!</h2>
<a href="{% url 'blog:create_blog' %}" class="btn btn-outline-info">Create Now</a>
{% endif %}

{% endblock %}