accounts/urls.py
from django.conf.urls import url
from . import views

app_name ='accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_user, name="signup_user"),
    url(r'^login/$', views.login_user, name="login_user"),
    url(r'^logout/$', views.logout_user, name="logout_user"),
    url(r'^profile/$', views.user_profile, name="user_profile"),
    url(r'^show/(?P<user_id>\d+)/$', views.show_user_profile, name="show_user_profile"),
]

blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'

urlpatterns = [
    url(r'^$', views.portfolio, name='portfolio'),
    url(r'^list/$', views.list, name='list'),
    url(r'^about/$', views.about, name="about"),
    url(r'^announcements/$', views.announcements, name="announcements"),
    url(r'^calenders/$', views.calenders, name="calenders"),
    url(r'^create/$', views.create_blog, name='create_blog'),
    url(r'^confirm-delete/(?P<blog_id>\d+)/$', views.delete_blog_confirmation, name='delete_blog_confirmation'),
    url(r'^delete/(?P<blog_id>\d+)/$', views.delete_blog, name='delete_blog'),
    url(r'^delete-review/(?P<blog_review_id>\d+)/$', views.delete_blog_review, name='delete_blog_review'),
    url(r'^comment/(?P<blog_id>\d+)/$', views.comment_blog, name='comment_blog'),
    url(r'^edit/(?P<blog_id>\d+)/$', views.edit_blog, name='edit_blog'),
    url(r'^(?P<blog_id>\d+)/$', views.blog_detail, name='blog_detail'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
#for using the media file variables
from django.conf import settings
#for static files(css)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#for media files(images)
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('blog.urls')),
    url(r'^accounts/', include('accounts.urls')),
]
#appending url for static_files(css)
urlpatterns += staticfiles_urlpatterns()
#appending url for media_file(images)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base-layout.html' %}

{% block content %}
<div>
    <h1>Blogapp</h1>
    <p>This is a blogapp created in Python. It utilises the Python web framework <a href="https://docs.djangoproject.com/en/2.2/">Django 2.2</a></p>
    <p>It provides following features: -</p>
    <ul>
        <li>Login</li>
        <li>Logout</li>
        <li>Signup(Creating user profile)</li>
        <li>Creating Blogs</li>
        <li>Editing Blogs</li>
        <li>Deleting Blogs</li>
        <li>Posting Comments</li>
        <li>Deleting Comments</li>
        <li>Editing User Profile</li>
        <li>Checking User Profiles</li>
    </ul>
</div>
{% endblock %}

templates/base-layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <!-- Link for using Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Link to Custom Css file -->
    <link rel="stylesheet" href="{% static 'style.css'%}">
    <title>Django Blog</title>
</head>
<body>
    <!-- Navigation Bar as the header -->
    <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'blog:portfolio' %}">Blogger</a>
        <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'blog:list' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'blog:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'accounts:logout_user' %}">Logout</a>
                <a class="nav-item nav-link" href="{% url 'blog:create_blog' %}">Create Blog</a>
                <a class="nav-item nav-link" href="{% url 'accounts:user_profile' %}">Profile</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'accounts:login_user' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'accounts:signup_user' %}">Sign Up</a>
            {% endif %}
            </div>
        </div>
        </div>
    </nav>
    </header>

    <main role="main" class="container">
            <div class="row">
              <div class="col-md-8">
                {% if messages %}
                    {% for msg in messages %}
                    <div class="alert alert-success">
                        {{ msg }}
                    </div>
                    {% endfor %}
                {% endif %}
                {% block content %}
                {% endblock %}
              </div>
              <div class="col-md-4">
                <div class="content-section">
                  <h3>Our Sidebar</h3>
                  <p class='text-muted'>Get Quick Information Here
                    <ul class="list-group">
                      <li class="list-group-item list-group-item-light"><a class="list-group-item-light" href="{% url 'blog:list' %}">Latest Posts</a></li>
                      <li class="list-group-item list-group-item-light"><a class="list-group-item-light" href="{% url 'blog:announcements' %}">Announcements</a></li>
                      <li class="list-group-item list-group-item-light"><a class="list-group-item-light" href="{% url 'blog:calenders' %}">Calenders</a></li>
                      <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                  </p>
                </div>
              </div>
            </div>
          </main>


    <!-- scripts for using bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/errors.html
{% extends 'base-layout.html' %}

{% block content%}
<h2 class="text-danger">{{msg}}</h2>
{% endblock %}

templates/informations.html
{% extends 'base-layout.html' %}

{% block content %}
<div>
    <h1>{{msg}}</h1>
</div>
{% endblock %}

templates/portfolio.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <!-- Link for using Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Link to Custom Css file -->
    <link rel="stylesheet" href="{% static 'portfolio.css'%}">
    <title>Django Blog</title>
</head>
<body>
<div class="container main">
    <h1 class="text">Blogapp</h1>
    <p>This is a blogapp created in Python. It utilises the Python web framework <a class="text-warning" href="https://docs.djangoproject.com/en/2.2/">Django 2.2</a></p>
    <p>Created By:- </p>
    <ul>
        <li>Ayush Gangwar</li>
        <li>Akash Chandra</li>
        <li>Ansh Pathak</li>
        <li>Vanshika Agarwal</li>
    </ul>
    <p>Guided By:- Mr. Shaktirish Kumar Agarwal
    (PGT Computer Science, Ben-Hur Public School)</p>
    <a class="btn btn-primary" href="{% url 'blog:list' %}">Enter Site</a>
</div>
<!-- scripts for using bootstrap -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>